In [5]:
print("stickaz")

stickaz


In [6]:
from numpy import arange

In [7]:
for i in arange(1,10,1):
    print("ciao")

ciao
ciao
ciao
ciao
ciao
ciao
ciao
ciao
ciao


In [8]:
{2,1,4}

{1, 2, 4}

In [9]:
{2,1,'ciao'}

{1, 2, 'ciao'}

In [10]:
{"carlo","antonio"}

{'antonio', 'carlo'}

In [12]:
a={1,2,1}

In [13]:
a

{1, 2}

In [14]:
tuple(a)

(1, 2)

In [15]:
list(a)

[1, 2]

In [16]:
import numpy as np

In [17]:
a=list(a)

In [18]:
a

[1, 2]

In [20]:
a < 1

False

In [21]:
a=np.array(a)

In [22]:
a


array([1, 2])

In [23]:
a>1

array([False,  True], dtype=bool)

In [24]:
b=list(a)

In [25]:
b


[1, 2]

In [26]:
c=b[1:]

In [27]:
c

[2]

In [28]:
c[0]=3

In [29]:
c

[3]

In [30]:
b

[1, 2]

In [47]:
first=np.arange(17,21)

In [49]:
first

array([17, 18, 19, 20])

In [50]:
myarr=np.array([first, first+5, first+10])

In [51]:
myarr

array([[17, 18, 19, 20],
       [22, 23, 24, 25],
       [27, 28, 29, 30]])

In [52]:
myarr[0]=18

In [53]:
first

array([17, 18, 19, 20])

In [54]:
myarr

array([[18, 18, 18, 18],
       [22, 23, 24, 25],
       [27, 28, 29, 30]])

In [55]:
import pandas as pd

In [57]:
labels=["a","b","c"]
my_data=[10,20,30]
arr=np.array(my_data)
d={"a":10,"b":20,"c":30}

In [58]:
pd.Series(my_data,labels)

a    10
b    20
c    30
dtype: int64

In [63]:
np.random.randn(2,3)

array([[ 0.5652898 ,  1.48985717, -3.02088443],
       [ 0.97108589,  1.42167345,  0.04394156]])

In [66]:
df=pd.DataFrame(np.random.randn(5,4),['a','b','c','d','e'],['X','Y','W','Z'])

In [67]:
df

X         Y         W         Z
a -1.089688  0.921814  1.671425 -2.685507
b -0.328431 -1.539218 -0.506578  1.542611
c  0.412317 -0.856539 -0.227278  1.023996
d -2.367161 -0.593921 -0.067868 -0.741348
e  0.359173 -1.439219  0.395220 -1.625423